# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main_sse.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('tools', 'tools'),
        ('config_manager.py', '.'),
        ('Database', 'Database'),
    ],
    hiddenimports=[
        'mcp',
        'mcp.server',
        'mcp.server.fastmcp',
        'fastmcp',
        'pydantic',
        'typing_extensions',
        'uvicorn',
        'uvicorn.main',
        'uvicorn.server',
        'uvicorn.config',
        'starlette',
        'starlette.applications',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.responses',
        'starlette.routing',
        'asyncio',
        'sqlite3',
        'json',
        'datetime',
        'pathlib',
        'os',
        'tools',
        'tools.persona_tools',
        'tools.memory_tools',
        'tools.viewpoint_tools',
        'tools.insight_tools',
        'tools.goal_tools',
        'tools.preference_tools',
        'tools.methodology_tools',
        'tools.focus_tools',
        'tools.prediction_tools',
        'tools.database_tools',
        'tools.base',
        'config_manager',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='UserBank_SSE_Core',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
) 